import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import InventoryCashRegister from '../src/components/InventoryCashRegister';
import { defaultCommands } from '../src/utils/workspaceCommands';
const visibleCommands = Object.fromEntries(Object.keys(defaultCommands).map((key) => [key, true]));

afterEach(() => { cleanup(); vi.restoreAllMocks(); });
it('hides command columns and individual buttons based on settings', () => {
  const records = [{ id: 'a', date: '2026-09-01', name: 'SUNIL', filledGoes14: 1, totalAmount: 100, paidAmount: 20, duesAmount: 80 }];
  const { rerender } = render(<InventoryCashRegister view="report" records={records} commands={{ ...defaultCommands, registerActions: false, registerPrintBill: false, registerPrintReport: false }} />);
  expect(screen.queryByRole('columnheader', { name: 'Actions' })).toBeNull();
  expect(screen.queryByRole('columnheader', { name: 'Print Bill' })).toBeNull();
  expect(screen.queryByRole('button', { name: 'Print Report' })).toBeNull();
  expect(screen.queryByRole('columnheader', { name: 'Remark' })).toBeNull();
  rerender(<InventoryCashRegister view="report" records={records} commands={{ ...visibleCommands, registerDelete: false }} />);
  expect(screen.queryByRole('button', { name: 'Delete', exact: true })).toBeNull();
  expect(screen.getByRole('button', { name: 'Modify' })).toBeTruthy();
  expect(screen.getByRole('button', { name: 'Print Bill' })).toBeTruthy();
  expect(screen.getByRole('columnheader', { name: 'Remark' })).toBeTruthy();
});
it('prints the visible register with summary and totals and omits action columns', () => {
  const popup = { document: { write: vi.fn(), close: vi.fn(), readyState: 'loading' }, addEventListener: vi.fn() };
  vi.spyOn(window, 'open').mockReturnValue(popup);
  const base = { date: '2026-09-01', village: 'Village', filledGoes14: 2, emptyIn14: 1, filledGoes19: 0, emptyIn19: 0, totalAmount: 100, paidAmount: 0, duesAmount: 100 };
  render(<InventoryCashRegister commands={visibleCommands} view="report" records={[{ ...base, id: 'a', name: 'SUNIL' }, { ...base, id: 'b', name: 'RAVI' }]} mutate={vi.fn()} onSaved={vi.fn()} />);
  fireEvent.change(screen.getByLabelText('Search register'), { target: { value: 'sunil' } });
  fireEvent.click(screen.getByRole('button', { name: 'Print Report' }));
  const html = popup.document.write.mock.calls[0][0];
  expect(html).toContain('SUNIL'); expect(html).not.toContain('RAVI');
  expect(html).toContain('14.2KG Due'); expect(html).toContain('TOTAL (1 entries)');
  expect(html).not.toContain('Actions'); expect(html).not.toContain('Print Bill');
  expect(html).not.toContain('<button'); expect(html).toContain('A4 landscape');
});
it('sorts amounts numerically and combines column filters with the due summary', () => {
  const base = { date: '2026-09-01', village: 'GARGATTA', contact: '', remark: '', filledGoes14: 2, emptyIn14: 1, filledGoes19: 0, emptyIn19: 0, paidAmount: 0 };
  render(<InventoryCashRegister commands={visibleCommands} view="report" records={[{ ...base, id: 'a', name: 'SUNIL', totalAmount: 100, duesAmount: 100 }, { ...base, id: 'b', name: 'RAVI', totalAmount: 20, duesAmount: 20 }]} mutate={vi.fn()} onSaved={vi.fn()} />);
  const report = within(screen.getByRole('table', { name: 'Inventory and cash register report' }));
  expect(within(report.getAllByRole('row')[0]).queryByRole('button')).toBeNull();
  expect(screen.queryByRole('button', { name: 'Sort By' })).toBeNull();
  expect(screen.queryByRole('button', { name: 'Filter With' })).toBeNull();
  fireEvent.change(screen.getByLabelText('Sort column'), { target: { value: 'totalAmount' } });
  expect(report.getAllByRole('row')[1].textContent).toContain('RAVI');
  fireEvent.change(screen.getByLabelText('Sort order'), { target: { value: 'desc' } });
  expect(report.getAllByRole('row')[1].textContent).toContain('SUNIL');
  fireEvent.change(screen.getByLabelText('Filter column'), { target: { value: 'duesAmount' } });
  fireEvent.change(screen.getByLabelText('Minimum'), { target: { value: '50' } });
  expect(report.queryByText('RAVI')).toBeNull();
  expect(screen.getByText('₹100')).toBeTruthy();
  fireEvent.change(screen.getByLabelText('Filter column'), { target: { value: 'name' } });
  fireEvent.change(screen.getByLabelText('Contains'), { target: { value: 'ravi' } });
  expect(report.getByText('No register entries found.')).toBeTruthy();
  fireEvent.change(screen.getByLabelText('Search register'), { target: { value: 'sunil' } });
  fireEvent.change(screen.getByLabelText('Period'), { target: { value: 'Today' } });
  fireEvent.change(screen.getByLabelText('Report From'), { target: { value: '2026-09-02' } });
  fireEvent.change(screen.getByLabelText('Report To'), { target: { value: '2026-09-03' } });
  expect(screen.getAllByRole('button', { name: 'Clear' })).toHaveLength(1);
  fireEvent.click(screen.getByRole('button', { name: 'Clear' }));
  expect(screen.getByLabelText('Search register').value).toBe('');
  expect(screen.getByLabelText('Period').value).toBe('All Time');
  expect(screen.getByLabelText('Report From').value).toBe('');
  expect(screen.getByLabelText('Report To').value).toBe('');
  expect(screen.getByLabelText('Sort column').value).toBe('');
  expect(screen.getByLabelText('Sort order').value).toBe('asc');
  expect(screen.getByLabelText('Filter column').value).toBe('name');
  expect(screen.getByLabelText('Contains').value).toBe('');
  expect(report.getByText('RAVI')).toBeTruthy();
  expect(report.getByText('SUNIL')).toBeTruthy();
});
it('saves cylinder movements and shows the computed balance in the report', async () => {
  const mutate = vi.fn(async ({ entry }) => ({ ...entry, duesAmount: 2626 }));
  const onSaved = vi.fn();
  const { rerender } = render(<InventoryCashRegister rates={[{ Item: '14.2 KG NON-SUBSIDIZED CYLINDER', RSP: 771 }, { Item: '19 KG FILLED LPG CYLINDER', RSP: 2007 }]} records={[]} mutate={mutate} onSaved={onSaved} />);
  expect(screen.getByLabelText('14.2KG Rate').value).toBe('771');
  expect(screen.getByLabelText('19KG Rate').value).toBe('2007');
  expect(screen.getByLabelText('14.2KG Rate').readOnly).toBe(true);
  for (const [label, value] of [['Name', 'SUNIL'], ['Panchayat / Village', 'GARGATTA'], ['Contact', '9876543210'], ['14.2KG Filled Goes', '6'], ['14.2KG Empty In', '1'], ['Paid Amount', '2000']]) fireEvent.change(screen.getByLabelText(label), { target: { value } });
  expect(screen.getByLabelText('Total Amount').value).toBe('4626');
  expect(screen.getByLabelText('Total Amount').readOnly).toBe(true);
  expect(screen.getByLabelText('Dues Amount').textContent).toBe('2,626');
  fireEvent.click(screen.getByRole('button', { name: 'Save Register Entry' }));
  await vi.waitFor(() => expect(onSaved).toHaveBeenCalled());
  expect(mutate.mock.calls[0][0]).toMatchObject({ mode: 'inventoryEntry', entry: { name: 'SUNIL', filledGoes14: 6, emptyIn14: 1, totalAmount: 4626, paidAmount: 2000 } });
  rerender(<InventoryCashRegister commands={visibleCommands} view="report" records={[onSaved.mock.calls[0][0]]} mutate={mutate} onSaved={onSaved} />);
  const report = within(screen.getByRole('table', { name: 'Inventory and cash register report' }));
  expect(report.getByText('SUNIL')).toBeTruthy();
  expect(report.getAllByText('2,626')).toHaveLength(2);
  fireEvent.click(report.getByRole('button', { name: 'Mark Paid' }));
  await vi.waitFor(() => expect(mutate).toHaveBeenCalledWith({ mode: 'inventoryPaid', id: onSaved.mock.calls[0][0].id, version: 0 }));
  fireEvent.click(report.getByRole('button', { name: 'Mark Unpaid' }));
  await vi.waitFor(() => expect(mutate).toHaveBeenCalledWith({ mode: 'inventoryUnpaid', id: onSaved.mock.calls[0][0].id, version: 0 }));
  fireEvent.click(report.getByRole('button', { name: 'Delete' }));
  expect(screen.getByRole('button', { name: 'Confirm Delete' })).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: 'Cancel Delete' }));
  fireEvent.click(report.getByRole('button', { name: 'Modify' }));
  expect(screen.getByLabelText('Name').value).toBe('SUNIL');
  expect(screen.getByRole('button', { name: 'Save Changes' })).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: 'Cancel Modify' }));
});
it('disables entry saving while cloud billing is unavailable', () => {
  render(<InventoryCashRegister commands={visibleCommands} records={[]} disabled mutate={vi.fn()} onSaved={vi.fn()} />);
  expect(screen.getByRole('button', { name: 'Save Register Entry' }).closest('fieldset').disabled).toBe(true);
});

