export const HINDI_FIELD_BEHAVIOR = {
  default: 'passthrough',
  'Consumer Name': 'dynamic_text',
  'Consumer No.': 'passthrough',
  'LPG ID': 'passthrough',
  Address: 'dynamic_address',
  'Mobile No.': 'passthrough',
  'Delivery Area': 'dynamic_place',
  'Delivery Man': 'dynamic_text',
  Product: 'mapped_value',
  HSN: 'passthrough',
  'Order Qty.': 'passthrough',
  'Order No.': 'passthrough',
  'Order Date': 'date_value',
  'Cash Memo No.': 'passthrough',
  'Cash Memo Date': 'date_value',
  'Last Delivery Date': 'date_value',
  'Consumer Package': 'mapped_value',
  'Connection/Qty': 'mapped_value',
  'EKYC Status': 'mapped_value',
  'Online Refill Payment status': 'mapped_value',
  'Payment Method': 'mapped_value',
  'Order Source': 'mapped_value',
  'Hose Expiry': 'passthrough',
  MI: 'mapped_value',
  'MI Status': 'mapped_value',
  'Sales Type': 'mapped_value',
  'CTC Status': 'mapped_value',
  'Subsidy Consumed': 'mapped_value',
  'Base Price (₹)': 'passthrough',
  'Delivery Charges (₹)': 'passthrough',
  'Cash & Carry Rebate (₹)': 'passthrough',
  'CGST (2.50%) (₹)': 'passthrough',
  'SGST (2.50%) (₹)': 'passthrough',
  'Taxable Amount (₹)': 'passthrough',
  'Advance (Online) (₹)': 'passthrough',
  'Net Payable (₹)': 'passthrough',
  'Total Amount (₹)': 'passthrough',
};

export const PASSTHROUGH_TOKEN_PATTERN = /^[0-9A-Z\-/.()&\s]+$/;
