export const HINDI_LABELS = {
  distributorCopy: 'वितरक प्रति',
  taxInvoice: 'कर चालान',
  declaration: 'घोषणा',
  signatureOfCustomer: 'उपभोक्ता के हस्ताक्षर',
  consumerName: 'उपभोक्ता नाम',
  consumerNo: 'उपभोक्ता संख्या',
  lpgId: 'एलपीजी आईडी',
  address: 'पता',
  mobileNo: 'मोबाइल नंबर',
  deliveryArea: 'वितरण क्षेत्र',
  deliveryStaff: 'डिलीवरी स्टाफ',
  productHsnQty: 'उत्पाद / एचएसएन / मात्रा',
  orderNoAndDate: 'ऑर्डर नंबर व दिनांक',
  cashMemoNoAndDate: 'कैश मेमो संख्या व दिनांक',
  productHsn: 'उत्पाद / एचएसएन',
  connectionQty: 'कनेक्शन / मात्रा',
  bookingSource: 'बुकिंग स्रोत',
  payment: 'भुगतान',
  category: 'श्रेणी',
  orderNo: 'ऑर्डर संख्या',
  orderDate: 'ऑर्डर दिनांक',
  cashMemoNo: 'कैश मेमो संख्या',
  cashMemoDate: 'कैश मेमो दिनांक',
  basePrice: 'मूल मूल्य (रु.)',
  deliveryCharges: 'डिलीवरी शुल्क (रु.)',
  cashCarryRebate: 'कैश एंड कैरी रिबेट (रु.)',
  taxableAmount: 'कर योग्य राशि (रु.)',
  cgst: 'सीजीएसटी (2.50%) (रु.)',
  sgst: 'एसजीएसटी (2.50%) (रु.)',
  totalAmount: 'कुल राशि (रु.)',
  advanceOnline: 'अग्रिम (ऑनलाइन) (रु.)',
  netPayable: 'शुद्ध देय (रु.)',
  eKyc: 'ई-केवाईसी',
  complaintNo: 'शिकायत नंबर',
};

export const HINDI_FIELD_LABELS = {
  'Consumer Name': HINDI_LABELS.consumerName,
  'Consumer No.': HINDI_LABELS.consumerNo,
  'LPG ID': HINDI_LABELS.lpgId,
  Address: HINDI_LABELS.address,
  'Mobile No.': HINDI_LABELS.mobileNo,
  'Delivery Area': HINDI_LABELS.deliveryArea,
  'Delivery Man': HINDI_LABELS.deliveryStaff,
  Product: 'उत्पाद',
  HSN: 'एचएसएन',
  'Order Qty.': 'मात्रा',
  'Order No.': HINDI_LABELS.orderNo,
  'Order Date': HINDI_LABELS.orderDate,
  'Cash Memo No.': HINDI_LABELS.cashMemoNo,
  'Cash Memo Date': HINDI_LABELS.cashMemoDate,
  'Last Delivery Date': 'पिछली डिलीवरी दिनांक',
  'Consumer Package': 'उपभोक्ता पैकेज',
  'Connection/Qty': HINDI_LABELS.connectionQty,
  'EKYC Status': HINDI_LABELS.eKyc,
  'Online Refill Payment status': 'ऑनलाइन रीफिल भुगतान स्थिति',
  'Payment Method': HINDI_LABELS.payment,
  'Order Source': HINDI_LABELS.bookingSource,
  'Hose Expiry': 'होज समाप्ति',
  MI: 'एमआई',
  'MI Status': 'एमआई स्थिति',
  'Sales Type': 'सेल्स प्रकार',
  'CTC Status': 'सीटीसी स्थिति',
  'Subsidy Consumed': 'सब्सिडी उपभोग',
  'Base Price (₹)': HINDI_LABELS.basePrice,
  'Delivery Charges (₹)': HINDI_LABELS.deliveryCharges,
  'Cash & Carry Rebate (₹)': HINDI_LABELS.cashCarryRebate,
  'CGST (2.50%) (₹)': HINDI_LABELS.cgst,
  'SGST (2.50%) (₹)': HINDI_LABELS.sgst,
  'Taxable Amount (₹)': HINDI_LABELS.taxableAmount,
  'Advance (Online) (₹)': HINDI_LABELS.advanceOnline,
  'Net Payable (₹)': HINDI_LABELS.netPayable,
  'Total Amount (₹)': HINDI_LABELS.totalAmount,
};
