export const HINDI_EXACT_OVERRIDES = {
  names: {
    Gaurav: 'गौरव',
  },
  villages: {},
  areas: {},
  addresses: {},
  general: {
    'HP Pay': 'एचपी पे',
    WhatsApp: 'व्हाट्सऐप',
    Cylinder: 'सिलेंडर',
  },
};

export const HINDI_VALUE_DICTIONARY = {
  Online: 'ऑनलाइन',
  Offline: 'ऑफलाइन',
  Paid: 'भुगतान किया गया',
  Unpaid: 'अभुगतान',
  Cash: 'नकद',
  UPI: 'यूपीआई',
  Card: 'कार्ड',
  'Pay On Delivery': 'डिलीवरी पर भुगतान',
  Delivered: 'वितरित',
  Pending: 'लंबित',
  Complete: 'पूर्ण',
  Yes: 'हाँ',
  No: 'नहीं',
  Done: 'पूर्ण',
  'Not Done': 'नहीं हुआ',
  Domestic: 'घरेलू',
  Commercial: 'व्यावसायिक',
  'Single Bottle Connection': 'सिंगल बॉटल कनेक्शन',
  'Double Bottle Connection': 'डबल बॉटल कनेक्शन',
  'HP Pay': 'एचपी पे',
  Whatsapp: 'व्हाट्सऐप',
  WhatsApp: 'व्हाट्सऐप',
  App: 'ऐप',
  Portal: 'पोर्टल',
};

export const HINDI_TOKEN_OVERRIDES = {
  road: 'रोड',
  rd: 'रोड',
  street: 'स्ट्रीट',
  st: 'स्ट्रीट',
  nagar: 'नगर',
  colony: 'कॉलोनी',
  mohalla: 'मोहल्ला',
  mohallaa: 'मोहल्ला',
  ward: 'वार्ड',
  house: 'हाउस',
  village: 'गांव',
  vill: 'गांव',
  post: 'पोस्ट',
  po: 'पोस्ट',
  tehsil: 'तहसील',
  block: 'ब्लॉक',
  dist: 'जिला',
  district: 'जिला',
  near: 'निकट',
  purwa: 'पुरवा',
  khurd: 'खुर्द',
  kalan: 'कलां',
  bazar: 'बाजार',
  bazaar: 'बाजार',
  chowk: 'चौक',
  market: 'मार्केट',
  no: 'नं',
  number: 'नंबर',
};
