import { useEffect, useMemo, useState } from 'react';
import { currentTime, loadAttendanceData, saveAttendanceData, todayKey } from './attendanceStore';
import './Attendance.css';

const STATUSES = ['Present', 'Half Day', 'Absent', 'Leave', 'Paid Leave'];
const blankForm = { name: '', address: '', contact: '', designation: '', wageType: 'Monthly Wage', wageAmount: '', employeeCode: '', monthlyBonus: '', advanceInstallment: '', manualDeduction: '', documents: [], photoDataUrl: '' };
const initials = (name = '') => name.split(' ').filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase() || 'E';
const toMinutes = (value = '') => {
  const text = String(value).trim();
  const twelveHour = text.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);
  if (twelveHour) { let hour = Number(twelveHour[1]) % 12; if (twelveHour[3].toUpperCase() === 'PM') hour += 12; return hour * 60 + Number(twelveHour[2]); }
  const twentyFourHour = text.match(/^(\d{1,2}):(\d{2})$/);
  return twentyFourHour ? Number(twentyFourHour[1]) * 60 + Number(twentyFourHour[2]) : null;
};

export default function AttendancePage({ loggedInUser, onClose, onEmployeeProfileOpen }) {
  const [data, setData] = useState(() => loadAttendanceData(loggedInUser));
  const [date, setDate] = useState(todayKey);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [showShiftSettings, setShowShiftSettings] = useState(false);
  const [payrollEmployeeId, setPayrollEmployeeId] = useState('');
  const [shiftSettings, setShiftSettings] = useState(() => loadAttendanceData(loggedInUser).settings?.shift || { start: '09:00', end: '18:00', grace: 10 });
  const [form, setForm] = useState(blankForm);
  const [editingId, setEditingId] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [showReport, setShowReport] = useState(false);
  const [reportMonth, setReportMonth] = useState(todayKey().slice(0, 7));
  const [salarySlip, setSalarySlip] = useState(null);
  const [message, setMessage] = useState('');
  const [now, setNow] = useState(() => new Date());
  const dayRecords = data.records[date] || {};
  const selectedHoliday = data.holidays?.[date] || '';
  const persist = (next) => { setData(next); saveAttendanceData(loggedInUser, next); };
  const notify = (text) => { setMessage(text); window.setTimeout(() => setMessage(''), 2400); };
  const employees = data.employees.filter((item) => {
    const status = dayRecords[item.id]?.status || 'Unmarked';
    return `${item.name} ${item.employeeCode} ${item.designation}`.toLowerCase().includes(search.toLowerCase()) && (statusFilter === 'All' || status === statusFilter);
  });
  const totals = useMemo(() => data.employees.reduce((result, item) => { const status = dayRecords[item.id]?.status || 'Unmarked'; result[status] = (result[status] || 0) + 1; return result; }, { Present: 0, 'Half Day': 0, Absent: 0, Leave: 0, Unmarked: 0 }), [data.employees, dayRecords]);
  const completed = data.employees.length ? Math.round((1 - totals.Unmarked / data.employees.length) * 100) : 0;
  const calendarMonthStart = new Date(Number(date.slice(0, 4)), Number(date.slice(5, 7)) - 1, 1);
  const calendarDays = new Date(Number(date.slice(0, 4)), Number(date.slice(5, 7)), 0).getDate();
  const calendarOffset = calendarMonthStart.getDay();
  const missingCheckIns = data.employees.filter((item) => dayRecords[item.id]?.status === 'Present' && !dayRecords[item.id]?.checkIn);
  const pendingCheckOuts = data.employees.filter((item) => dayRecords[item.id]?.checkIn && !dayRecords[item.id]?.checkOut);
  const lateEmployees = data.employees.filter((item) => { const checkIn = toMinutes(dayRecords[item.id]?.checkIn); return checkIn !== null && checkIn > toMinutes(shiftSettings.start) + Number(shiftSettings.grace || 0); });
  const overtimeMinutes = data.employees.reduce((total, item) => { const checkOut = toMinutes(dayRecords[item.id]?.checkOut); const shiftEnd = toMinutes(shiftSettings.end); return total + (checkOut !== null && shiftEnd !== null ? Math.max(0, checkOut - shiftEnd) : 0); }, 0);
  const daysInReportMonth = new Date(Number(reportMonth.slice(0, 4)), Number(reportMonth.slice(5, 7)), 0).getDate();
  const reportRows = useMemo(() => data.employees.map((employee) => { const counts = { Present: 0, 'Half Day': 0, Absent: 0, Leave: 0, 'Paid Leave': 0 }; const daily = {}; Object.entries(data.records).filter(([day]) => day.startsWith(reportMonth)).forEach(([day, records]) => { const status = records[employee.id]?.status; daily[Number(day.slice(-2))] = status || ''; if (status in counts) counts[status] += 1; }); const workingDays = counts.Present + counts['Half Day'] * .5; const payableDays = workingDays + counts['Paid Leave']; const rate = Number(employee.wageAmount || 0); const grossWage = employee.wageType === 'Daily Wage' ? payableDays * rate : (rate / daysInReportMonth) * payableDays; const bonus = Number(employee.monthlyBonus || 0); const deduction = Number(employee.advanceInstallment || 0) + Number(employee.manualDeduction || 0); const wage = Math.max(0, grossWage + bonus - deduction); return { employee, counts, daily, workingDays, payableDays, grossWage, bonus, deduction, wage }; }), [data, reportMonth, daysInReportMonth]);
  const updateRecord = (id, changes) => persist({ ...data, records: { ...data.records, [date]: { ...dayRecords, [id]: { ...(dayRecords[id] || {}), ...changes } } } });
  const saveShiftSettings = () => { persist({ ...data, settings: { ...(data.settings || {}), shift: shiftSettings } }); setShowShiftSettings(false); notify('Shift settings saved.'); };
  const toggleHoliday = () => { if (selectedHoliday) { if (!window.confirm(`Remove ${selectedHoliday} holiday?`)) return; const { [date]: removed, ...rest } = data.holidays || {}; persist({ ...data, holidays: rest }); return; } const name = window.prompt('Holiday name for selected date:'); if (name?.trim()) persist({ ...data, holidays: { ...(data.holidays || {}), [date]: name.trim() } }); };
  const shareSalarySlip = (row) => { const phone = String(row.employee.contact || '').replace(/\D/g, ''); const text = `Salary Slip%0AEmployee: ${encodeURIComponent(row.employee.name)}%0AMonth: ${encodeURIComponent(new Date(`${reportMonth}-01T12:00:00`).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' }))}%0APayable days: ${row.payableDays}%0ANet payable: ₹${row.wage.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`; window.open(`https://wa.me/${phone ? `91${phone.slice(-10)}` : ''}?text=${text}`, '_blank', 'noopener,noreferrer'); };
  const markAll = (status) => { const rows = Object.fromEntries(data.employees.map((item) => [item.id, { ...(dayRecords[item.id] || {}), status }])); persist({ ...data, records: { ...data.records, [date]: rows } }); notify(`All employees marked ${status.toLowerCase()}.`); };
  const resetDate = () => { if (!window.confirm(`Reset all attendance for ${date}?`)) return; const { [date]: removed, ...records } = data.records; persist({ ...data, records }); notify('Selected date reset successfully.'); };
  const openNew = () => { setEditingId(null); setForm(blankForm); setShowForm(true); };
  const openEdit = (employee) => { setEditingId(employee.id); setForm({ ...blankForm, ...employee }); setShowForm(true); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const payrollEmployee = data.employees.find((employee) => employee.id === payrollEmployeeId) || null;
  const updatePayrollEmployee = (changes) => { if (!payrollEmployee) return; persist({ ...data, employees: data.employees.map((employee) => employee.id === payrollEmployee.id ? { ...employee, ...changes } : employee) }); };
  const uploadDocument = (event) => { const file = event.target.files?.[0]; if (!file || !payrollEmployee) return; if (file.size > 900000) return notify('Please select a document under 900 KB.'); const reader = new FileReader(); reader.onload = () => { const documents = [...(payrollEmployee.documents || []), { id: `${Date.now()}`, name: file.name, type: file.type, dataUrl: reader.result }]; updatePayrollEmployee({ documents }); notify('Document added to employee vault.'); }; reader.readAsDataURL(file); event.target.value = ''; };
  const handleEmployeePhotoChange = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith('image/')) return notify('Please select an image for the employee photo.'); if (file.size > 900000) return notify('Employee photo must be under 900 KB.'); const reader = new FileReader(); reader.onload = () => setForm((current) => ({ ...current, photoDataUrl: reader.result })); reader.readAsDataURL(file); event.target.value = ''; };
  const removeDocument = (documentId) => updatePayrollEmployee({ documents: (payrollEmployee?.documents || []).filter((document) => document.id !== documentId) });
  const saveEmployee = (event) => { event.preventDefault(); if (!form.name.trim()) return notify('Employee name is required.'); if (editingId) { persist({ ...data, employees: data.employees.map((item) => item.id === editingId ? { ...item, ...form, name: form.name.trim() } : item) }); notify('Employee details updated.'); } else { persist({ ...data, employees: [...data.employees, { ...form, id: `${Date.now()}${Math.random().toString(36).slice(2)}`, name: form.name.trim() }] }); notify('Employee added successfully.'); } setShowForm(false); setEditingId(null); setForm(blankForm); };
  const removeEmployee = (employee) => { if (!window.confirm(`Remove ${employee.name}?`)) return; const records = Object.fromEntries(Object.entries(data.records).map(([key, value]) => { const { [employee.id]: removed, ...rest } = value; return [key, rest]; })); persist({ employees: data.employees.filter((item) => item.id !== employee.id), records }); };
  useEffect(() => {
    const closeOnBackdrop = (event) => {
      if (salarySlip && !event.target.closest('.salary-slip') && !event.target.closest('.whatsapp-slip-action')) setSalarySlip(null);
      else if (showReport && !event.target.closest('.attendance-report')) setShowReport(false);
    };
    document.addEventListener('pointerdown', closeOnBackdrop);
    return () => document.removeEventListener('pointerdown', closeOnBackdrop);
  }, [showReport, salarySlip]);
  useEffect(() => { const interval = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(interval); }, []);
  const exportReportCsv = () => { const header = ['Employee', 'Employee ID', ...Array.from({ length: daysInReportMonth }, (_, index) => String(index + 1)), 'Present', 'Half Day', 'Paid Leave', 'Leave', 'Absent', 'Working Days', 'Payable Days', 'Wage']; const rows = reportRows.map((row) => [row.employee.name, row.employee.employeeCode || '', ...Array.from({ length: daysInReportMonth }, (_, index) => row.daily[index + 1] || 'Unmarked'), row.counts.Present, row.counts['Half Day'], row.counts['Paid Leave'], row.counts.Leave, row.counts.Absent, row.workingDays, row.payableDays, row.wage]); const csv = [header, ...rows].map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); const link = document.createElement('a'); link.href = url; link.download = `attendance-${reportMonth}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <section className="attendance-page">
    <style>{`.employee-photo-upload{display:flex;align-items:center;gap:6px;color:#60758a;font-size:11px;font-weight:700}.employee-photo-upload input{max-width:145px;padding:5px!important;font-size:10px!important}.employee-photo-upload img{width:32px;height:32px;border-radius:5px;object-fit:cover}.employee-photo-upload button{padding:5px;border:0;border-radius:5px;color:#a43d3d;background:#fff0f0;font:inherit;font-size:10px;font-weight:700;cursor:pointer}`}</style>
    <header className="attendance-hero"><div><p>HR & WORKFORCE</p><h1>Attendance Centre</h1><span>Daily attendance, employee records and payroll in one workspace.</span></div><div className="attendance-hero-actions"><button className="attendance-report-button" onClick={() => setShowReport(true)}>Attendance Report</button><button className="attendance-report-button" onClick={onEmployeeProfileOpen}>Employee Profile</button><button className="attendance-primary" onClick={openNew}>+ Add employee</button><button className="attendance-corner-close" aria-label="Close attendance" title="Close" onClick={onClose}>×</button></div></header>
    <div className="smart-command-bar"><div><span>Smart attendance check</span><b>{totals.Unmarked} pending updates</b></div><div><span>Check-in exceptions</span><b>{missingCheckIns.length}</b></div><div><span>Check-out pending</span><b>{pendingCheckOuts.length}</b></div><div><span>Shift</span><b>{shiftSettings.start} – {shiftSettings.end}</b></div><button type="button" onClick={() => setStatusFilter('Unmarked')}>Show pending</button><button type="button" onClick={() => setStatusFilter('All')}>Clear filter</button><button type="button" onClick={() => setShowShiftSettings((value) => !value)}>Shift settings</button><button type="button" onClick={toggleHoliday}>{selectedHoliday ? 'Remove holiday' : 'Mark holiday'}</button><button type="button" className="smart-export" onClick={exportReportCsv}>Export month CSV</button></div>
    <div className="shift-live-summary"><span>Late arrivals: <b>{lateEmployees.length}</b></span><span>Overtime logged: <b>{Math.floor(overtimeMinutes / 60)}h {overtimeMinutes % 60}m</b></span><span>Grace period: <b>{shiftSettings.grace} min</b></span></div>
    {selectedHoliday && <div className="holiday-banner">Holiday: <b>{selectedHoliday}</b> · Attendance is optional for this selected date.</div>}
    {showShiftSettings && <section className="shift-settings"><div><span className="section-label">SHIFT POLICY</span><h3>Set working shift</h3></div><label>Start time<input type="time" value={shiftSettings.start} onChange={(e) => setShiftSettings({ ...shiftSettings, start: e.target.value })} /></label><label>End time<input type="time" value={shiftSettings.end} onChange={(e) => setShiftSettings({ ...shiftSettings, end: e.target.value })} /></label><label>Grace minutes<input type="number" min="0" max="120" value={shiftSettings.grace} onChange={(e) => setShiftSettings({ ...shiftSettings, grace: Number(e.target.value) })} /></label><button className="attendance-primary" onClick={saveShiftSettings}>Save shift</button></section>}
    <div className="attendance-livebar"><div><span>Selected date</span><b>{new Date(`${date}T12:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).replace(/ /g, '-')}</b></div><div><span>Current time</span><b>{now.toLocaleTimeString('en-GB', { hour12: false })}</b></div><div><span>Live status</span><b>Attendance open</b></div></div>
    <section className="attendance-calendar"><div className="attendance-calendar__header"><div><span className="section-label">ATTENDANCE CALENDAR</span><h2>{calendarMonthStart.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</h2></div><div className="calendar-legend"><span><i className="calendar-dot calendar-dot--present" />Present</span><span><i className="calendar-dot calendar-dot--absent" />Absent</span><span><i className="calendar-dot calendar-dot--holiday" />Holiday</span></div></div><div className="calendar-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day) => <b key={day}>{day}</b>)}{Array.from({ length: calendarOffset }, (_, index) => <span key={`blank-${index}`} />)}{Array.from({ length: calendarDays }, (_, index) => { const day = index + 1; const key = `${date.slice(0, 7)}-${String(day).padStart(2, '0')}`; const records = data.records[key] || {}; const statuses = Object.values(records).map((record) => record.status); const isSelected = key === date; const holiday = data.holidays?.[key]; const tone = holiday ? 'holiday' : statuses.includes('Absent') ? 'absent' : statuses.includes('Present') ? 'present' : ''; return <button type="button" key={key} className={`calendar-day calendar-day--${tone} ${isSelected ? 'calendar-day--selected' : ''}`} onClick={() => setDate(key)}><strong>{String(day).padStart(2, '0')}</strong><small>{holiday || (statuses.length ? `${statuses.filter((status) => status === 'Present').length} P` : '—')}</small></button>; })}</div></section>
    {message && <div className="attendance-toast">{message}</div>}
    <div className="attendance-overview"><div className="attendance-date-card"><span className="section-label">ATTENDANCE DATE</span><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /><strong>{new Date(`${date}T12:00:00`).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short', year: 'numeric' })}</strong></div><div className="attendance-progress"><div><span className="section-label">DAILY REGISTER</span><strong>{completed}% completed</strong></div><div className="progress-track"><i style={{ width: `${completed}%` }} /></div><small>{data.employees.length - totals.Unmarked} of {data.employees.length} employees updated</small></div><div className="bulk-actions"><button className="mark-all-button" disabled={!data.employees.length} onClick={() => markAll('Present')}>All present</button><button className="mark-all-absent" disabled={!data.employees.length} onClick={() => markAll('Absent')}>All absent</button><button className="reset-attendance" disabled={!data.employees.length} onClick={resetDate}>Reset date</button></div></div>
    <div className="attendance-stats">{[['Present', 'On duty'], ['Half Day', 'Half day'], ['Absent', 'Not at work'], ['Leave', 'Approved leave']].map(([key, label]) => <div key={key} className={`attendance-stat attendance-stat--${key.replace(' ', '-').toLowerCase()}`}><span>{label}</span><strong>{totals[key]}</strong><b>{key}</b></div>)}</div>
    {showForm && <section className="employee-add-card professional-add"><div><span className="section-label">EMPLOYEE DIRECTORY</span><h2>{editingId ? 'Edit employee details' : 'Add a team member'}</h2><p>These details will also be used in reports and ID cards.</p></div><form onSubmit={saveEmployee}><input autoFocus value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Full name *" /><input value={form.employeeCode} onChange={(e) => setForm({ ...form, employeeCode: e.target.value })} placeholder="Employee ID / code" /><input value={form.contact} onChange={(e) => setForm({ ...form, contact: e.target.value })} placeholder="Contact number" /><input value={form.designation} onChange={(e) => setForm({ ...form, designation: e.target.value })} placeholder="Designation" /><label className="employee-photo-upload">Employee photo<input type="file" accept="image/*" onChange={handleEmployeePhotoChange} />{form.photoDataUrl && <><img src={form.photoDataUrl} alt="Employee preview" /><button type="button" onClick={() => setForm({ ...form, photoDataUrl: '' })}>Remove</button></>}</label><input className="employee-address" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} placeholder="Address" /><select value={form.wageType} onChange={(e) => setForm({ ...form, wageType: e.target.value })}><option>Monthly Wage</option><option>Daily Wage</option></select><input type="number" min="0" value={form.wageAmount} onChange={(e) => setForm({ ...form, wageAmount: e.target.value })} placeholder="Wage amount" /><button className="attendance-primary">{editingId ? 'Update employee' : 'Save employee'}</button><button type="button" className="form-cancel" onClick={() => setShowForm(false)}>Cancel</button></form></section>}
    <div className="attendance-main-grid"><section className="attendance-table-card"><div className="attendance-table-title"><div><span className="section-label">DAILY REGISTER</span><h2>Team attendance</h2></div><label className="employee-search">Search <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Employee name" /></label></div>{data.employees.length === 0 ? <div className="attendance-empty"><h3>Your employee directory is empty</h3><button className="attendance-primary" onClick={openNew}>Add first employee</button></div> : <div className="attendance-table-wrap"><table><thead><tr><th>Employee</th><th>Attendance</th><th>Check in</th><th>Check out</th><th>Actions</th></tr></thead><tbody>{employees.map((employee) => { const record = dayRecords[employee.id] || {}; return <tr key={employee.id}><td><div className="employee-cell"><span className="employee-avatar">{initials(employee.name)}</span><div><strong>{employee.name}</strong><small>{employee.employeeCode || 'No employee ID'} · {employee.designation || 'Employee'}</small></div></div></td><td><select className={`status-select status-select--${(record.status || 'unmarked').replace(' ', '-').toLowerCase()}`} value={record.status || ''} onChange={(e) => updateRecord(employee.id, { status: e.target.value })}><option value="">Select status</option>{STATUSES.map((status) => <option key={status}>{status}</option>)}</select></td><td>{record.checkIn ? <input className="time-edit" value={record.checkIn} onChange={(e) => updateRecord(employee.id, { checkIn: e.target.value })} /> : <button className="time-action" onClick={() => updateRecord(employee.id, { status: record.status || 'Present', checkIn: currentTime() })}>Check in now</button>}</td><td>{record.checkOut ? <input className="time-edit time-edit--out" value={record.checkOut} onChange={(e) => updateRecord(employee.id, { checkOut: e.target.value })} /> : <button className="time-action" disabled={!record.checkIn} onClick={() => updateRecord(employee.id, { checkOut: currentTime() })}>Check out</button>}</td><td><div className="employee-actions"><button className="edit-employee" onClick={() => openEdit(employee)}>Edit</button><button className="remove-employee" onClick={() => removeEmployee(employee)}>Remove</button></div></td></tr>; })}</tbody></table></div>}</section><aside className="attendance-side-panel"><div className="monthly-card"><span className="section-label">MONTHLY SNAPSHOT</span><h2>{new Date(`${date}T12:00:00`).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</h2><p>Open Attendance Report for detailed salary calculations and individual salary slips.</p></div><div className="attendance-note"><b>Editable time records</b><p>Click the saved Check in or Check out value to correct the time manually.</p></div></aside></div>
    {showReport && <div className="attendance-report-overlay"><section className="attendance-report"><header><div><span className="section-label">PAYROLL REPORT</span><h2>Day-wise Attendance & Wage Report</h2><p>Every date in the selected month is shown employee-wise.</p></div><div><label>Report month<input type="month" value={reportMonth} onChange={(e) => setReportMonth(e.target.value)} /></label><button className="attendance-close report-close" onClick={() => setShowReport(false)}>Close</button></div></header><div className="report-period"><span>{new Date(`${reportMonth}-01T12:00:00`).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</span><small>Total days: <b>{daysInReportMonth}</b> · P=Present, A=Absent, H=Half Day, L=Leave, PL=Paid Leave</small><button className="attendance-primary" onClick={() => window.print()}>Print report</button></div><div className="report-table-wrap report-table-wrap--daily"><table><thead><tr><th>Employee</th>{Array.from({ length: daysInReportMonth }, (_, index) => <th className="daily-report-head" key={index}>{String(index + 1).padStart(2, '0')}</th>)}<th>Total</th><th>Present</th><th>Working</th><th>Paid leave</th><th>Leave</th><th>Half</th><th>Absent</th><th>Wage</th><th>Slip</th></tr></thead><tbody>{reportRows.map((row) => <tr key={row.employee.id}><td className="report-employee"><b>{row.employee.name}</b><small>{row.employee.employeeCode || 'No ID'} · {row.employee.designation || 'Employee'}</small></td>{Array.from({ length: daysInReportMonth }, (_, index) => { const status = row.daily[index + 1]; const statusCode = status === 'Present' ? 'P' : status === 'Absent' ? 'A' : status === 'Half Day' ? 'H' : status === 'Paid Leave' ? 'PL' : status === 'Leave' ? 'L' : '—'; return <td className={`daily-status daily-status--${statusCode.toLowerCase().replace('—', 'empty')}`} title={status || 'Unmarked'} key={index}>{statusCode}</td>; })}<td>{daysInReportMonth}</td><td>{row.counts.Present}</td><td><b>{row.workingDays}</b></td><td>{row.counts['Paid Leave']}</td><td>{row.counts.Leave}</td><td>{row.counts['Half Day']}</td><td>{row.counts.Absent}</td><td className="report-wage">₹{row.wage.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</td><td><button className="salary-slip-button" onClick={() => setSalarySlip(row)}>Salary slip</button></td></tr>)}</tbody></table></div><footer><span>{reportRows.length} employees · Salary includes Paid Leave.</span><strong>Total payable: ₹{reportRows.reduce((total, row) => total + row.wage, 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}</strong></footer></section></div>}
    {salarySlip && <div className="attendance-report-overlay salary-slip-overlay"><section className="salary-slip"><header><div><span className="section-label">SALARY SLIP</span><h2>{loggedInUser?.dealerName || 'Cashmemo'}</h2><p>{new Date(`${reportMonth}-01T12:00:00`).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</p></div><button className="attendance-close report-close" onClick={() => setSalarySlip(null)}>Close</button></header><div className="slip-employee"><div><span>Employee name</span><b>{salarySlip.employee.name}</b></div><div><span>Employee ID</span><b>{salarySlip.employee.employeeCode || '—'}</b></div><div><span>Designation</span><b>{salarySlip.employee.designation || 'Employee'}</b></div><div><span>Wage type</span><b>{salarySlip.employee.wageType || 'Monthly Wage'}</b></div></div><div className="slip-grid"><div><span>Total calendar days</span><b>{daysInReportMonth}</b></div><div><span>Present days</span><b>{salarySlip.counts.Present}</b></div><div><span>Half days</span><b>{salarySlip.counts['Half Day']}</b></div><div><span>Leave days</span><b>{salarySlip.counts.Leave}</b></div><div><span>Absent days</span><b>{salarySlip.counts.Absent}</b></div><div><span>Payable working days</span><b>{salarySlip.workingDays}</b></div></div><div className="slip-total"><span>Net payable salary</span><strong>₹{salarySlip.wage.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</strong></div><footer><small>This is a system-generated salary slip.</small><button className="attendance-primary" onClick={() => window.print()}>Print salary slip</button></footer></section></div>}
    <section className="payroll-vault-panel"><div><span className="section-label">PAYROLL & DOCUMENT VAULT</span><h3>Employee financial profile</h3></div><select value={payrollEmployeeId} onChange={(e) => setPayrollEmployeeId(e.target.value)}><option value="">Select employee</option>{data.employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select>{payrollEmployee && <><label>Monthly bonus<input type="number" min="0" value={payrollEmployee.monthlyBonus || ''} onChange={(e) => updatePayrollEmployee({ monthlyBonus: e.target.value })} /></label><label>Loan installment<input type="number" min="0" value={payrollEmployee.advanceInstallment || ''} onChange={(e) => updatePayrollEmployee({ advanceInstallment: e.target.value })} /></label><label>Other deduction<input type="number" min="0" value={payrollEmployee.manualDeduction || ''} onChange={(e) => updatePayrollEmployee({ manualDeduction: e.target.value })} /></label><label className="vault-upload">Upload document<input type="file" accept="image/*,.pdf" onChange={uploadDocument} /></label><div className="vault-documents">{(payrollEmployee.documents || []).length ? payrollEmployee.documents.map((document) => <span key={document.id}><a href={document.dataUrl} target="_blank" rel="noreferrer">{document.name}</a><button onClick={() => removeDocument(document.id)}>×</button></span>) : <small>No documents uploaded</small>}</div></>}</section>
    {salarySlip && <div className="salary-breakdown-card"><div><span>Gross earnings</span><b>₹{salarySlip.grossWage.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</b></div><div><span>Bonus</span><b>+ ₹{salarySlip.bonus.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</b></div><div><span>Total deductions</span><b>− ₹{salarySlip.deduction.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</b></div><div className="salary-breakdown-card__payable"><span>Net payable</span><b>₹{salarySlip.wage.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</b></div></div>}
    {salarySlip && <button className="whatsapp-slip-action" onClick={() => shareSalarySlip(salarySlip)}>Share salary slip on WhatsApp</button>}
  </section>;
}
