import { useState } from 'react';
import { loadAttendanceData, saveAttendanceData } from './attendanceStore';
import './Attendance.css';

export default function EmployeeProfilePage({ loggedInUser, onClose }) {
  const [data, setData] = useState(() => loadAttendanceData(loggedInUser));
  const [employeeId, setEmployeeId] = useState('');
  const [payrollDraft, setPayrollDraft] = useState({ monthlyBonus: '', advanceInstallment: '', manualDeduction: '' });
  const [message, setMessage] = useState('');
  const employee = data.employees.find((item) => item.id === employeeId);
  const save = (next) => { setData(next); saveAttendanceData(loggedInUser, next); };
  const update = (changes) => save({ ...data, employees: data.employees.map((item) => item.id === employeeId ? { ...item, ...changes } : item) });
  const notify = (text) => { setMessage(text); window.setTimeout(() => setMessage(''), 2200); };
  const uploadDocument = (event) => { const file = event.target.files?.[0]; if (!file || !employee) return; if (file.size > 900000) return notify('Please select a document under 900 KB.'); const reader = new FileReader(); reader.onload = () => { update({ documents: [...(employee.documents || []), { id: `${Date.now()}`, name: file.name, type: file.type, dataUrl: reader.result }] }); notify('Document added to vault.'); }; reader.readAsDataURL(file); event.target.value = ''; };
  const removeDocument = (id) => update({ documents: (employee?.documents || []).filter((document) => document.id !== id) });
  const selectEmployee = (id) => { const selected = data.employees.find((item) => item.id === id); setEmployeeId(id); setPayrollDraft({ monthlyBonus: selected?.monthlyBonus || '', advanceInstallment: selected?.advanceInstallment || '', manualDeduction: selected?.manualDeduction || '' }); };
  const savePayroll = () => { if (!employee) return; update(payrollDraft); notify('Payroll adjustments saved.'); };
  return <section className="attendance-page employee-profile-page"><header className="attendance-hero"><div><p>EMPLOYEE DIRECTORY</p><h1>Employee Profile</h1><span>Manage employee payroll adjustments and important documents.</span></div><button className="attendance-close" onClick={onClose}>Back to Attendance</button></header>{message && <div className="attendance-toast">{message}</div>}<section className="employee-profile-workspace"><label>Select employee<select value={employeeId} onChange={(e) => selectEmployee(e.target.value)}><option value="">Choose employee</option>{data.employees.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.employeeCode || 'No ID'}</option>)}</select></label>{!employee ? <div className="attendance-empty"><h3>Select an employee</h3><p>Employee payroll details and documents will appear here.</p></div> : <><div className="employee-profile-summary"><div><span>Employee</span><b>{employee.name}</b></div><div><span>Designation</span><b>{employee.designation || 'Employee'}</b></div><div><span>Contact</span><b>{employee.contact || '—'}</b></div><div><span>Wage</span><b>{employee.wageType || 'Monthly Wage'} · ₹{Number(employee.wageAmount || 0).toLocaleString('en-IN')}</b></div></div><div className="profile-section-grid"><section><span className="section-label">PAYROLL ADJUSTMENTS</span><h2>Salary additions & deductions</h2><div className="profile-fields"><label>Monthly bonus<input type="number" min="0" value={payrollDraft.monthlyBonus} onChange={(e) => setPayrollDraft({ ...payrollDraft, monthlyBonus: e.target.value })} placeholder="0" /></label><label>Loan / advance installment<input type="number" min="0" value={payrollDraft.advanceInstallment} onChange={(e) => setPayrollDraft({ ...payrollDraft, advanceInstallment: e.target.value })} placeholder="0" /></label><label>Other deduction<input type="number" min="0" value={payrollDraft.manualDeduction} onChange={(e) => setPayrollDraft({ ...payrollDraft, manualDeduction: e.target.value })} placeholder="0" /></label></div><button className="attendance-primary profile-save" onClick={savePayroll}>Save payroll changes</button><p className="profile-help">These adjustments apply automatically in the monthly attendance report and salary slip.</p></section><section><span className="section-label">DOCUMENT VAULT</span><h2>Employee documents</h2><label className="document-upload">+ Upload Aadhaar, PAN, bank proof or joining document<input type="file" accept="image/*,.pdf" onChange={uploadDocument} /></label><div className="document-list">{(employee.documents || []).length ? employee.documents.map((document) => <div key={document.id}><a href={document.dataUrl} target="_blank" rel="noreferrer">{document.name}</a><button onClick={() => removeDocument(document.id)}>Remove</button></div>) : <p>No documents uploaded yet.</p>}</div></section></div></>}</section></section>;
}
